---
immiopkgs:
  - git-core
  - redis-server
  - tmux
  - rabbitmq-server
  - postgresql
  - postgresql-contrib
rubyver: '2.1.0'
rubygems:
  "rails":
    gemver: '4.0.2'
  "passenger":
    gemver: '4.0.35'
nginxparams:
  user: 'vagrant'
  group: 'vagrant'
  gid: '1000'
  password: '$6$hgWepssv$nwQ6SUsgvqEzn7ru1lq2KNllLiVRKrX8NqNukQhMjj5RnGS9j6RblRXF8rg8pTK5Pe74AROVe371Btkl.fJPO/'
  conffile: '/opt/nginx/conf/nginx.conf'
nginxvhosts:
  "serverparams":
    docroot: '/var/www/balder/public/'
    server_name: 'dev.balder.com'
    order: '01'
    listenport: '80'
  "prod":
    docroot: '/var/www/balder/public/'
    server_name: 'balder.com'
    order: '10'
    listenport: '80'
dependentpkgs:
  - nodejs
  - libcurl4-openssl-dev
  - libpq-dev
  - libpq5
passengerparams:
  max_pool_size: 15
  min_instances: 5
  pool_idle_time: 5
  buffers: 16
  buffer_size: 32k
  buffer_response: 'off'
subdirs:
  - '/var/www'
  - '/var/www/balder'
  - '/opt/nginx'
