---
pmasterip: 192.168.129.11
pmasterecsip: 10.39.162.72
rubyver: '2.1.0'
nginxparams:
  user: 'pixlr'
  group: 'web'
  gid: '1001'
  password: '$6$n1ZLNYG/$rHMtCLPF08SPuBu0NzbE.tJwSehwjzU6qWkX.czU0MgtpfRkDjyNSv/CWWbmhUhlwJqx8eFKW5G5sMxuvQOfT.'
  conffile: '/opt/nginx/conf/nginx.conf'
nginxserverparams:
  client_max_body_size: '100M'
  sendfile: 'on'
  keepalive_timeout: '65'
  tcp_nodelay: 'on'
  gzip: 'on'
  error_log: '/dev/null crit'
  access_log: 'off'
nginxvhosts:
  "serverparams":
    docroot: '/var/www/pixlr/public/'
    server_name: 'pixlr.com'
    order: '01'
    listenport: '80'
  "prod":
    docroot: '/var/www/pixlr/public/'
    server_name: 'pixlr.com'
    order: '10'
    listenport: '80'
  "prodssl":
    docroot: '/var/www/pixlr/public/'
    server_name: 'pixlr.com'
    order: '11'
    listenport: '443'
  "dev":
    docroot: '/var/www/developer/'
    server_name: 'developer.pixlr.com'
    order: '12'
    listenport: '80'
  "stage":
    docroot: '/var/www/pixlr_stage/trunk/public'
    server_name: 'pixlr.com'
    order: '13'
    listenport: '80'
  "vagrant":
    docroot: '/var/www/vagrant'
    server_name: 'vagrant.pixlr.com'
    order: '14'
    listenport: '80'
  "immio":
    docroot: '/var/www/immio/'
    server_name: 'imm.io www.imm.io old.imm.io test.imm.io'
    order: '15'
    listenport: '80'
  "close":
    docroot: '/var/www/pixlr/public/'
    server_name: 'pixlr.com'
    order: '99'
    listenport: '80'
dependentpkgs:
  - subversion
  - libcurl4-openssl-dev
  - libpq-dev
  - libpq5
subdirs:
  - '/var/www'
  - '/var/www/pixlr'
  - '/var/www/immio'
  - '/var/www/developer'
  - '/opt/nginx'
rubygems:
  "passenger":
    gemver: '4.0.35'
passengerparams:
  max_pool_size: 15
  min_instances: 5
  pool_idle_time: 5
  buffers: 16
  buffer_size: 32k
  buffer_response: 'off'
pixlrscripts:
  - backup
  - deploy
  - deploy-all
  - nag_nrpe.sh
  - slaves
  - sync
pixlrappslaves:
  - 10.142.226.74
  - 192.168.159.39
  - 192.168.159.43
  - 192.168.168.187
  - 192.168.175.104
  - 192.168.175.111
  - 192.168.168.75
  - 192.168.169.31
pixlrmongodb:
  - 192.168.181.246
  - 192.168.181.253
  - 192.168.182.191
pixlrmongodbport: 27017
cronjobs:
  "security-updates":
    command: '/usr/bin/apt-get upgrade -o Dir::Etc::SourceList=/etc/apt/security.sources.list'
    user: 'root'
    hour: '9'
    minute: '0'
    ensure: 'present'
  "mongo-backup":
    command: '/root/backup'
    user: 'root'
    hour: '8'
    minute: '30'
    ensure: 'present'
  "unison-sync":
    command: '/root/sync public'
    user: 'root'
    hour: '*'
    minute: '*'
    ensure: 'present'
  "pixlr-backup":
    command: '/home/pixlr/pixlr-bk /var/www/pixlr/public/news/ pixlr 192.168.181.246:27017 192.168.181.253:27017 192.168.182.191:27017'
    user: 'pixlr'
    hour: '*'
    minute: '15'
    ensure: 'present'
cronjobsall:
  "pixlr-temp-cleanup":
    command: 'find /var/www/pixlr/public/_temp/ -type f -ctime +2 | xargs rm'
    user: 'pixlr'
    hour: '*'
    minute: '*/30'
    ensure: 'present'
javaparams:
  version: 7u51
  build: b13
  jdkdir: /opt
  dlurlbase: 'http://download.oracle.com/otn-pub/java/jdk'
  os: 'linux-x64'
  unpackdir: 'jdk1.7.0_51'
sbtparams: 
  dlurlbase: 'http://repo.scala-sbt.org/scalasbt/sbt-native-packages/org/scala-sbt/sbt'
  version: 0.13.1
  pkgname: sbt.deb
  user: debian
  group: debian
sbtconfigopts:
  - Dscala.concurrent.context.minThreads=2
  - XX:+CMSClassUnloadingEnabled
  - XX:+UseConcMarkSweepGC
  - XX:MaxPermSize=724M
nagiosparams:
  url: 'http://assets.nagios.com/downloads/nagiosxi'
  releaseyear: '2012'
  releasever: 'xi-2012r2.8c'
nagiospkgs:
  - nagios-nrpe-server
  - nagios-plugins
  - nagios-snmp-plugins
nagioschecks:
  - check_init_service
  - check_services
  - check_cpu_stats.sh
  - custom_check_mem
  - custom_check_procs
  - check_open_files.pl
  - check_netstat.pl
  - check_passenger.sh
  - check_mem
nrpeparams: 
  checkdir: '/usr/lib/nagios/plugins'
  startscript: 'nagios-nrpe-server'
nrpehosts: 
  - 127.0.0.1
  - 132.188.71.0/24
  - 54.225.81.79
